name: BasementLib
main: it.ohalee.basementlib.bukkit.loader.BukkitLoaderPlugin
version: ${pluginVersion}
api-version: 1.13
author: ohAlee
softdepend:
  - "PlaceholderAPI"
commands:
  basement:
    aliases:
      - "basementlib"